
backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Icon Key", name: "icon_key", widget: "select", options: ["supply-chain", "cold-chain", "inventory", "delivery", "warehousing"] }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "team"
    label: "Team Members"
    folder: "content/team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Company Name", name: "company", widget: "string" }
      - { label: "Contact Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Message", name: "message", widget: "text" }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5 }
      - { label: "Image", name: "image", widget: "image", required: false }

  - name: "jobs"
    label: "Job Listings"
    folder: "content/jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Department", name: "department", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Type", name: "type", widget: "select", options: ["Full-time", "Part-time", "Contract"] }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Requirements", name: "requirements", widget: "markdown" }
      - { label: "Benefits", name: "benefits", widget: "markdown", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Story", name: "story", widget: "text" }
          - { label: "Mission", name: "mission", widget: "text" }
          - { label: "Vision", name: "vision", widget: "text" }
          - { label: "Years Experience", name: "years_experience", widget: "string", default: "20+" }
          - { label: "Hero Image", name: "image", widget: "image" }

      - label: "Company Info"
        name: "company"
        file: "content/pages/company.md"
        fields:
          - { label: "Company Name", name: "name", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Registration Number", name: "registration", widget: "string" }
          - { label: "Founded Year", name: "founded", widget: "number" }

  - name: "industries"
    label: "Industries"
    folder: "content/industries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Services", name: "services", widget: "list", field: { label: "Service", name: "service", widget: "string" } }
      - { label: "Order", name: "order", widget: "number", default: 1 }
